version: '2'
services:
  app:
    build: ./
    ports:
      - '3001:3000'
      - '8081:8080'
    depends_on:
      - mongo
    networks:
      - appnetwork
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge