version: '3'
services:
  app:
    image: wks-tippmeister
    build: ./
    ports:
      - '3000:3000'
      - '8080:8080'
    depends_on:
      - mongo
    networks:
      - appnetwork
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge