version: '3'
services:
  app:
    image: wks-tippmeister
    build: ./
    ports:
      - '3000:3000'
      - '8080:8080'
    environment:
      - MONGO_ADDRESS=mongo
    depends_on:
      - mongo
    networks:
      - appnetwork
  mongo:
    image: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - '27017:27017'
    restart: always
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge